# Generated by Django 5.0.6 on 2024-05-31 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_alter_book_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.FloatField()),
                ('density', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TrashCan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('s', 'small'), ('m', 'medium'), ('l', 'large')], default='s', max_length=1)),
                ('items', models.ManyToManyField(help_text='Items to put in trashcan.', to='catalog.item')),
            ],
        ),
    ]
